/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JButton;

/**
 *
 * @author DELL
 */
public class ConfirmTransaction extends javax.swing.JFrame {

    /**
     * Creates new form confirmTransaction
     */
    public ConfirmTransaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        filmName = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        theater = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        buttonBuy = new javax.swing.JButton();
        showIDTrans = new javax.swing.JLabel();
        showName = new javax.swing.JLabel();
        showDate = new javax.swing.JLabel();
        showTime = new javax.swing.JLabel();
        showTheater = new javax.swing.JLabel();
        showPrice = new javax.swing.JLabel();
        nameFilm = new javax.swing.JLabel();
        dateSchedule = new javax.swing.JLabel();
        timeSchedule = new javax.swing.JLabel();
        theaterSchedule = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        title.setText("Transaction Confirmation");

        filmName.setText("Film:");

        date.setText("Date:");

        theater.setText("Theater:");

        price.setText("Total Price:");

        time.setText("Time:");

        buttonBuy.setText("Buy");

        nameFilm.setText("jLabel1");

        dateSchedule.setText("jLabel1");

        timeSchedule.setText("jLabel1");

        theaterSchedule.setText("jLabel1");

        totalPrice.setText("jLabel1");

        buttonCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filmName)
                            .addComponent(date)
                            .addComponent(time)
                            .addComponent(theater)
                            .addComponent(price))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showIDTrans)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(showPrice)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalPrice))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(showTheater)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(theaterSchedule))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(showTime)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(timeSchedule))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(showName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameFilm))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(showDate)
                                    .addGap(35, 35, 35)
                                    .addComponent(dateSchedule)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(buttonBuy)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCancel)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(title)
                .addGap(42, 42, 42)
                .addComponent(showIDTrans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmName)
                    .addComponent(showName)
                    .addComponent(nameFilm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(showDate)
                    .addComponent(dateSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time)
                    .addComponent(showTime)
                    .addComponent(timeSchedule))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(theater)
                    .addComponent(showTheater)
                    .addComponent(theaterSchedule))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(showPrice)
                    .addComponent(totalPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBuy)
                    .addComponent(buttonCancel))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuy;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateSchedule;
    private javax.swing.JLabel filmName;
    private javax.swing.JLabel nameFilm;
    private javax.swing.JLabel price;
    private javax.swing.JLabel showDate;
    private javax.swing.JLabel showIDTrans;
    private javax.swing.JLabel showName;
    private javax.swing.JLabel showPrice;
    private javax.swing.JLabel showTheater;
    private javax.swing.JLabel showTime;
    private javax.swing.JLabel theater;
    private javax.swing.JLabel theaterSchedule;
    private javax.swing.JLabel time;
    private javax.swing.JLabel timeSchedule;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables

    public void setConfirm(String filmName, Date dateBuy, String time, int theater, int price){
        DateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String dateStr = date.format(dateBuy);
        
        this.nameFilm.setText(filmName);
        this.dateSchedule.setText(dateStr);
        this.timeSchedule.setText(time);
        this.theaterSchedule.setText(Integer.toString(theater));
        this.totalPrice.setText(Integer.toString(price));
    }    

    public JButton getButtonBuy() {return buttonBuy;}
    public JButton getButtonCancel() {return buttonCancel;}
    public void actionListener(ActionListener listen){
        this.buttonBuy.addActionListener(listen);
        this.buttonCancel.addActionListener(listen);
    }

    
    
}
