/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JButton;

/**
 *
 * @author DELL
 */
public class confirmTransaction extends javax.swing.JFrame {

    /**
     * Creates new form confirmTransaction
     */
    public confirmTransaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        idTrans = new javax.swing.JLabel();
        filmName = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        theater = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        buttonBuy = new javax.swing.JButton();
        showIDTrans = new javax.swing.JLabel();
        showName = new javax.swing.JLabel();
        showDate = new javax.swing.JLabel();
        showTime = new javax.swing.JLabel();
        showTheater = new javax.swing.JLabel();
        showPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        title.setText("Transaction Confirmation");

        idTrans.setText("ID Transaction: ");

        filmName.setText("Film:");

        date.setText("Date:");

        theater.setText("Theater:");

        price.setText("Total Price:");

        time.setText("Time:");

        buttonBuy.setText("Buy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTrans)
                            .addComponent(filmName)
                            .addComponent(date)
                            .addComponent(time)
                            .addComponent(theater)
                            .addComponent(price))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showPrice)
                            .addComponent(showTheater)
                            .addComponent(showTime)
                            .addComponent(showDate)
                            .addComponent(showName)
                            .addComponent(showIDTrans)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(buttonBuy)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(title)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTrans)
                    .addComponent(showIDTrans))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmName)
                    .addComponent(showName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(showDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time)
                    .addComponent(showTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(theater)
                    .addComponent(showTheater))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(showPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(buttonBuy)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirmTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirmTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirmTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirmTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new confirmTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuy;
    private javax.swing.JLabel date;
    private javax.swing.JLabel filmName;
    private javax.swing.JLabel idTrans;
    private javax.swing.JLabel price;
    private javax.swing.JLabel showDate;
    private javax.swing.JLabel showIDTrans;
    private javax.swing.JLabel showName;
    private javax.swing.JLabel showPrice;
    private javax.swing.JLabel showTheater;
    private javax.swing.JLabel showTime;
    private javax.swing.JLabel theater;
    private javax.swing.JLabel time;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    public void setConfirm(int id, String name, Date dateBuy, String time, int theater, int price){
        DateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String dateStr = date.format(dateBuy);
        
        this.showIDTrans.setText(Integer.toString(id));
        this.showName.setText(name);
        this.showDate.setText(dateStr);
        this.showTime.setText(time);
        this.showTheater.setText(Integer.toString(theater));
        this.showPrice.setText(Integer.toString(price));
    }

    public int getID(){return Integer.parseInt(showIDTrans.getText());}

    public JButton getButtonBuy() {return buttonBuy;}
    public void actionListener(ActionListener listen){
        this.buttonBuy.addActionListener(listen);
    }

    
    
}
